aws-cloudformation/aws-cloudformation-resource-providers-redshift

eventsubscription/aws-redshift-eventsubscription.json
eventsubscription/resource-role.yaml
eventsubscription/src/main/java/software/amazon/redshift/eventsubscription/UpdateHandler.java

Fix EventSubscription cfn validate

Fix EventSubscription cfn validate

---

scheduledaction/aws-redshift-scheduledaction.json
scheduledaction/resource-role.yaml

Fix ScheduledAction cfn validate

Fix ScheduledAction cfn validate

---

endpoint-authorization/aws-redshift-endpointauthorization.json
endpoint-authorization/resource-role.yaml

Fix EndpointAuthorization cfn validate

Fix EndpointAuthorization cfn validate

---

endpoint-access/aws-redshift-endpointaccess.json
endpoint-access/resource-role.yaml

Fix EndpointAccess cfn validate

Fix EndpointAccess cfn validate

---

endpoint-authorization/.gitignore
endpoint-authorization/aws-redshift-endpointauthorization.json

- The original VPC ID's regex is problematic
- Update the regex

Fix VPC ID regex for EndpointAuthorization

---

aws-redshift-scheduledaction/aws-redshift-scheduledaction.json

- ScheduledAction would fail Contract Tests V2
- Udate Schema

Fix ScheduledAction's Schema in order to meet Contract Tests V2 requirements

---

aws-redshift-clusterparametergroup/aws-redshift-clusterparametergroup.json
aws-redshift-clusterparametergroup/resource-role.yaml

- ClusterParameterGroup would fail Contract Tests V2
- Update Schema

Fix ClusterParameterGroup's Schema in order to meet Contract Tests V2 requirements

---

aws-redshift-clusterparametergroup/aws-redshift-clusterparametergroup.json
aws-redshift-clusterparametergroup/docs/README.md
aws-redshift-clusterparametergroup/docs/parameter.md
aws-redshift-clusterparametergroup/docs/tag.md
aws-redshift-clusterparametergroup/pom.xml
aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/BaseHandlerStd.java
aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/ClientBuilder.java
aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/CreateHandler.java
aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/DeleteHandler.java
aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/ListHandler.java
aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/ModifyTagsRequest.java
aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/ReadHandler.java
aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/Translator.java
aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/UpdateHandler.java
aws-redshift-clusterparametergroup/src/test/java/software/amazon/redshift/clusterparametergroup/AbstractTestBase.java
aws-redshift-clusterparametergroup/src/test/java/software/amazon/redshift/clusterparametergroup/CreateHandlerTest.java
aws-redshift-clusterparametergroup/src/test/java/software/amazon/redshift/clusterparametergroup/DeleteHandlerTest.java
aws-redshift-clusterparametergroup/src/test/java/software/amazon/redshift/clusterparametergroup/ListHandlerTest.java
aws-redshift-clusterparametergroup/src/test/java/software/amazon/redshift/clusterparametergroup/ReadHandlerTest.java
aws-redshift-clusterparametergroup/src/test/java/software/amazon/redshift/clusterparametergroup/TestUtils.java
aws-redshift-clusterparametergroup/src/test/java/software/amazon/redshift/clusterparametergroup/UpdateHandlerTest.java

- Change the auto-gen primary identifier functionality
- improve the parameter applying functionality
- code improvement
*Test passed*
- Unit test
- Integ test
- CTv2

Refactor ClusterParameterGroup

---

aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/UpdateHandler.java

[Fix] apply null safe logic to ClusterParameterGroup Update Handler

---

aws-redshift-clusterparametergroup/aws-redshift-clusterparametergroup.json
aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/Translator.java

[chg] remove drift detection for ClusterParameterGroup's tag

---

aws-redshift-clustersubnetgroup/aws-redshift-clustersubnetgroup.json
aws-redshift-clustersubnetgroup/docs/tag.md
aws-redshift-clustersubnetgroup/resource-role.yaml
aws-redshift-clustersubnetgroup/src/main/java/software/amazon/redshift/clustersubnetgroup/Translator.java
aws-redshift-clustersubnetgroup/src/test/java/software/amazon/redshift/clustersubnetgroup/TestUtils.java

[chg] remove drift detection for ClusterSubnetGroup's tag

---

aws-redshift-eventsubscription/aws-redshift-eventsubscription.json
aws-redshift-eventsubscription/docs/tag.md
aws-redshift-eventsubscription/src/main/java/software/amazon/redshift/eventsubscription/Translator.java
aws-redshift-eventsubscription/src/test/java/software/amazon/redshift/eventsubscription/AbstractTestBase.java

[chg] remove drift detection for EventSubscription's tag

---

aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/BaseHandlerStd.java
aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/CreateHandler.java
aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/DeleteHandler.java
aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/ReadHandler.java
aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/UpdateHandler.java

[fix] fix ClusterParameterGroup callGraph typo

---

aws-redshift-endpointaccess/aws-redshift-endpointaccess.json
aws-redshift-endpointaccess/docs/README.md
aws-redshift-endpointaccess/docs/vpcendpoint.md

Update CTv2 readOnly settings - list down parent node(s) only

---

aws-redshift-endpointaccess/aws-redshift-endpointaccess.json
aws-redshift-endpointaccess/docs/README.md
aws-redshift-endpointaccess/docs/vpcendpoint.md

[fix] temp workaround for fixing GetAtt and comply CTv2

---

aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/UpdateHandler.java

We're researching a customer issue where our handler triggered a parametergroup update when it should not.
This commit logs the previousModel and desiredModel (parametergroup before and after the customer cfn request), which should help us debug the issue.

Add parametergroup update logs

---

aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/Translator.java
aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/UpdateHandler.java
aws-redshift-cluster/src/test/java/software/amazon/redshift/cluster/TestUtils.java
aws-redshift-cluster/src/test/java/software/amazon/redshift/cluster/UpdateHandlerTest.java

The unit test before has many repeating fields and variables. This commit refactors the code to be cleaner.

Refactor UpdateHandler unit test

---

aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/UpdateHandler.java

Remove extra semicolon from update handler

---

aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/UpdateHandler.java

The update-cluster can be tagged with only resource-level tags, stack level tags are not added as the part of this process to the resource. Stack Level Tags: are tags specified in the AWS console, they should be shared by all resources created inside that stack. Resource Level Tags: are tags specified in CloudFormation templates.
Note: Redshift does not support system level tags

Add support for stack tags in modify-cluster

---

aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/UpdateHandler.java

Required for updating `ResourcePolicy` and `DeferMaintenanance` without it's identifiers. From `DescribeCluster`, `ClusterNamespaceArn` and `DeferMaintenanceIdentifier` values are collected and used during update actions. Since there's a `DescribeCluster` call in Read handler as well, call graph name here should be different than the Read handler `DescribeCluster` call graph name.

Add describeClusters for Update handler.

---

aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/CreateHandler.java

This CR refactors the logic related to updating the default group name. We access the input model object directly instead of through callback functions. The CR will fix failures in cluster parameter group creation when group name is not provided.
Tested locally when group name is provided and group name is not provided Testing commands:
1. sample json
{
"desiredResourceState": {
"Description": "Redshift ClusterParameterGroup Contract Test V2",
"ParameterGroupName": "vramanet-cpg",
"ParameterGroupFamily": "redshift-1.0",
"Parameters": [
{
"ParameterName": "require_ssl",
"ParameterValue": "true"
}
]
},
"previousResourceState": {},
"logicalResourceIdentifier": "vramanet-cpg"
}
2. sam local start-lambda
3. cfn invoke resource CREATE create-clusterparametergroup.json …

Refactor cluster parameter group name default value logic when group name is not provided

---

aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/ReadHandler.java

This CR refactors the logic related to handling the exception when resource policy API in not supported. We would be getting a
UnsupportedOperationException in those regions. This is irrespective of whether we provide a resource policy during create or not as we are calling the get resource api policy irrespective. We modify the logic to remove the flag and handle the exception in unsupported exception only and not redshift exception.
Tested locally in the region af-south-1
Testing commands:
1. sample json
{
"desiredResourceState": {
"ClusterIdentifier": "redshiftcanarycluster-07o2ewecv9cl",
"ClusterType": "multi-node",
"NodeType": "ra3.4xlarge",
"NumberOfNodes": 2,
"DBName": "dev",
"MasterUsername": "master",
"MasterUserPassword": "uQ6Lt4cDFk",
"AvailabilityZoneRelocation": true, …

Create cluster failure due to resource policy not supported in certain regions

---

aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/ReadHandler.java

This error handling is required for backward compatibility. Without this exception handling, existing customers creating or updating their clusters will see an error with permission issues - "is not authorized to perform: redshift:GetResourcePolicy", as Read handler is trying to hit getResourcePolicy APIs to get namespaceResourcePolicy details

Handle backward compatibility while creating a Cluster

---

aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/Translator.java
aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/UpdateHandler.java
aws-redshift-cluster/src/test/java/software/amazon/redshift/cluster/UpdateHandlerTest.java

Before this fix, if cx doesn't provide a track name in the CFN template, we'll call the create-cluster w/o the track name, and create-cluster by default creats a cluster w/ "current" track. When cx does add "current" track to the template, our code thinks it needs an update and calls modify-cluster w/ "current" track, and modify-cluster throws exception that the cluster is already on "current" track.
We should have handled this and not call modify-cluster when track name changes from null to "current".
This commit checks the previousModel's track setup and calls modify-cluster accordingly
Tested locally in Docker, previously failing modify-cluster is now passing. The code also handles when modify-cluster needs to be called but track doesn't need to be modified …

Check track name changes before modify-cluster
