- aws-redshift-endpointaccess/aws-redshift-endpointaccess.json
- aws-redshift-endpointaccess/docs/README.md
- `ClusterIdentifier` and `SubnetGroupName` are required by the Front-End
- Put both properties to `required` field
> Add properties ClusterIdentifier and SubnetGroupName as `required` for EndpointAccess

- aws-redshift-cluster/aws-redshift-cluster.json
- aws-redshift-cluster/docs/README.md
- aws-redshift-cluster/pom.xml
[Description/Design]:
Update cluster IAM roles to 50 from 10. it was changed to 50 : According to the config read by the coral service default value is set to 50, hence there are no limitation from the API side. https://code.amazon.com/packages/RedshiftConfigurations/blobs/mainline/--/configuration/RedshiftConfigurations/ServerConfigurations/CORAL_SERVICE/CoralService.yml#L283. Add new redshift SDK version dependency in POM file  to support above change.
> Update cluster IAM roles to 50 from 10

- aws-redshift-clusterparametergroup/docs/tag.md
- aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/Translator.java
- aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/UpdateHandler.java
- aws-redshift-clusterparametergroup/src/test/java/software/amazon/redshift/clusterparametergroup/ReadHandlerTest.java
- Originally, we reset/update all parameters if the Update Handler is called, regardless of whether they're required to be reset/update indeed or not. This logic result in unnecessarily cluster reboot after the update.
- We change the log to only reset/update specific parameters if needed.
> [Fix] ClusterParameterGroup would only reset/update only if needed

- aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/BaseHandlerStd.java
- aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/UpdateHandler.java
- aws-redshift-cluster/src/test/java/software/amazon/redshift/cluster/UpdateHandlerTest.java
Before this commit, we didn't have logs to see which attributes values changed triggered the ModifyCluster.
This commit:
1) adds log to log each attribute change, so we'll be able to troubleshoot when ModifyCluster is not expected to happen. 
2) removes some unused imports
> Log which attributes trigger ModifyCluster

- aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/UpdateHandler.java
- aws-redshift-cluster/src/test/java/software/amazon/redshift/cluster/TestUtils.java
- aws-redshift-cluster/src/test/java/software/amazon/redshift/cluster/UpdateHandlerTest.java
The previous refactor change accidentally removes EnhandcedVpcRouting, this commit adds this attribute back, so its changes in Cluster model will be detected.
This commit also adds unit test to ensure all attributes for detecting modifyCluster are present
> Detect EnhancedVpcRouting attribute change in modifyClusterRequest

- aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/UpdateHandler.java
- aws-redshift-clusterparametergroup/src/test/java/software/amazon/redshift/clusterparametergroup/TestUtils.java
- aws-redshift-clusterparametergroup/src/test/java/software/amazon/redshift/clusterparametergroup/UpdateHandlerTest.java
Before this commit, we sometimes update wlm_json_configuration when we should not. We decide whether to update (call
modifyClusterParameterGroup) by checking the wlm_json_configuration provided by cx in cfn template vs. the one we fetch by calling describe API. But the wlm_json_configuration returned by describe API is sanitized by Redshift backend. So many times wlm_json_configuration comparison would tell us we should update.
This commit sanitizes both new and old (from api) wlm_json_configuration then compare if they are equal. We can do a more precise job by comparing if the two string evaluates to the same JSON object, but too much effort involved for now.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
> Sanitize wlm_json_configuration then compare

- aws-redshift-cluster/aws-redshift-cluster.json
- aws-redshift-clusterparametergroup/aws-redshift-clusterparametergroup.json
- aws-redshift-clustersubnetgroup/aws-redshift-clustersubnetgroup.json
- aws-redshift-endpointaccess/aws-redshift-endpointaccess.json
- aws-redshift-endpointauthorization/aws-redshift-endpointauthorization.json
- aws-redshift-eventsubscription/aws-redshift-eventsubscription.json
- aws-redshift-scheduledaction/aws-redshift-scheduledaction.json
Most of the failing contract tests right now are because we didn't give CFN permission to call describeResource or describeTags APIs.
This commit gives the CFN those permissions in every handler, in case in the future CFN tests start requiring more read permissions again and break the existing tests.
> Add permission for CFN Contract Test

- aws-redshift-clusterparametergroup/aws-redshift-clusterparametergroup.json
The latest contract test handler requires DescribeClusterParameter permissions. This commit adds the permission
> Add redshift:DescribeClusterParameters for contract test

- aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/UpdateHandler.java
- aws-redshift-cluster/src/test/java/software/amazon/redshift/cluster/TestUtils.java
- aws-redshift-cluster/src/test/java/software/amazon/redshift/cluster/UpdateHandlerTest.java
Before we were hardcoding the ARN partition to be "aws", and in Gov region ARN was not correctly built and APIs failed.
This commit creates the ARN based on the aws partition in the request.
> Construct cluster ARN using correct partition

- aws-redshift-cluster/aws-redshift-cluster.json
Right now if users provide SnapshotIdentifier on the Cluster in CFN template, after its creation, drift detection will display the cluster's status as drifted. In this case, we restore the cluster from the snapshot provided, and the snapshot identifier should not be considered as part of the drift detection.
Adding it to writeOnly properties will prevent this from happening
> Prevent cluster drift detection on SnapshotIdentifier

- aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/BaseHandlerStd.java
- aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/UpdateHandler.java
- aws-redshift-cluster/src/test/java/software/amazon/redshift/cluster/UpdateHandlerTest.java
After the modify-cluster call, it takes 1 or more seconds for the ACTIVE cluster to be changed to MODIFYING, we used to call stabilizer right after the modify-cluster call, and stabilizer immediately returns that the cluster is ACTIVE, because the cluster didn't get a chance to be changed to be MODIFYING, which incorrectly tells CFN that the modify-cluster is done.
We wait for 10 seconds just to be on the safe side, it's longer than we need most of the time, but 10 seconds is acceptable because the modify-cluster usually takes minutes for the cluster to be ACTIVE again.
> Wait 10 seconds after modify-cluster call

- aws-redshift-cluster/aws-redshift-cluster.json
- aws-redshift-cluster/docs/README.md
- aws-redshift-cluster/pom.xml
- aws-redshift-cluster/resource-role.yaml
- aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/CallbackContext.java
- aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/CreateHandler.java
- aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/ReadHandler.java
- aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/Translator.java
- aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/UpdateHandler.java
- aws-redshift-cluster/src/test/java/software/amazon/redshift/cluster/CreateHandlerTest.java
- aws-redshift-cluster/src/test/java/software/amazon/redshift/cluster/UpdateHandlerTest.java
- aws-redshift-cluster/template.yml
1. Remove describeCluster call from CreateHandler.
2. Code Refactor wrt ResourcePolicy API changes.
3. Remove Id property from schema readonly properties.
4. Update redshift awssdk and projectlombok versions.
5. Add EC2 permission for the Cfn Iam role to create instance and manage them.
6. Add CloudWatch putmetrics permission to write logs to CloudFormation.
7. Increase MemorySize in template.yml file.
> Remove describeCluster call from CreateHandler

- aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/UpdateHandler.java
- aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/CreateHandler.java
- aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/Translator.java
- aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/UpdateHandler.java
- aws-redshift-clusterparametergroup/src/test/java/software/amazon/redshift/clusterparametergroup/TestUtils.java
- aws-redshift-clusterparametergroup/src/test/java/software/amazon/redshift/clusterparametergroup/UpdateHandlerTest.java
The create-parameter-group and modify tags can be tagged with only resource-level tags as of now, stack level tags are not added as the part of this process to the resource.
Stack Level Tags: are tags specified in the AWS console, they should be shared by all resources created inside that stack.
Resource Level Tags: are tags specified in CloudFormation templates.
This commit provides support to add stack level tags to the resources
> Add stack tag support to cluster-parameter-group resource

- aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/ReadHandler.java
Handle GetResourcePolicy exception in case of not authorized error. This is required for backward compatibility and not to cause errors while creating Clusters with existing permissions set. Also removed unused code in Read Handler.
Exceptions will be thrown if `NamespaceResourcePolicy` is set on cfn template but `redshift:GetResourcePolicy` permissions are not included in the roles.
> Resource policy exception

- aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/CreateHandler.java
- aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/ReadHandler.java
- aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/Translator.java
1. Read Handler - NoOp method for handling `GetresourcePolicy` Exceptions - this method will assign empty value to `NamespaceResourcePolicy` if there are permission issues that restrict accessing GetResourcePolicy API. Also, empty value is assigned if NamespaceResourcePolicy is not found on the Cluster. Assigning empty value will suppress NamespaceResourcePolicy propery in  `CreateCluster` Cfn response.
2. Translator - Update logger to handle empty NamespaceResourcePolicy.
3. Create Handler - Minor logger change.
> No-Op method for handling GetResourcePolicy exceptions.

- aws-redshift-endpointaccess/aws-redshift-endpointaccess.json
CTV2 contract tests were failing for Endpoint access because of missing EC2 permissions. Ran ctv2 tests locally for endpoint access following this guide. Contract tests passed locally
> Fix CTv2 Contract tests

- aws-redshift-cluster/aws-redshift-cluster.json
- aws-redshift-cluster/docs/README.md
- aws-redshift-cluster/pom.xml
- aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/BaseHandlerStd.java
- aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/Translator.java
- aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/UpdateHandler.java
- aws-redshift-cluster/src/test/java/software/amazon/redshift/cluster/AbstractTestBase.java
- aws-redshift-cluster/src/test/java/software/amazon/redshift/cluster/CreateHandlerTest.java
- aws-redshift-cluster/src/test/java/software/amazon/redshift/cluster/TestUtils.java
- aws-redshift-cluster/src/test/java/software/amazon/redshift/cluster/UpdateHandlerTest.java
The changes provide Cloudformation support for Secrets Manager integration with Redshift clusters. With this new feature, customers can opt in to store their cluster's admin credentials in a service linked secret in Secrets Manager. It allows us to create/modify/restore Redshift clusters with Secrets Manager support using the Cloudformation template. The changes in this request allow us to use create-cluster, modify-cluster, restore-from-cluster-snapshot APIs for Redshift clusters when opting in to this feature.
We are adding a new boolean parameter "ManageMasterPassword" to allow customers to opt in to this feature and another parameter "MasterPasswordSecretKmsKeyId" allows customers to specify the key ID of the KMS key in the customer account which will be used to encrypt the cluster …
> Cloudformation support for Secrets Manager Integration

- aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/ReadHandler.java
ResourcePolicy API is not enabled in all the regions. We need to handle unsupported exceptions in regions where this API is not supported.
> Handle Unsupported ResourcePolicy Exceptions.

- aws-redshift-cluster/.rpdk-config
- aws-redshift-cluster/template.yml
- aws-redshift-clusterparametergroup/.rpdk-config
- aws-redshift-clusterparametergroup/template.yml
- aws-redshift-clustersubnetgroup/.rpdk-config
- aws-redshift-clustersubnetgroup/template.yml
- aws-redshift-endpointaccess/.rpdk-config
- aws-redshift-endpointaccess/template.yml
- aws-redshift-endpointauthorization/.rpdk-config
- aws-redshift-endpointauthorization/template.yml
- aws-redshift-eventsubscription/.rpdk-config
- aws-redshift-eventsubscription/template.yml
- aws-redshift-scheduledaction/.rpdk-config
- aws-redshift-scheduledaction/template.yml
This CR contains changes related to JDK 17 runtime upgrade for all Redshift CFN resources. This change includes runtime upgrade in .rpdk-config and template.yml as per upgrade guidance.
Testing:
1. Run contract test for the resources after upgrade.
2. Verify CTV2 passes for each resource.
> Changes related to JDK 17 runtime upgrade

- aws-redshift-eventsubscription/aws-redshift-eventsubscription.json
- aws-redshift-eventsubscription/docs/README.md
- aws-redshift-eventsubscription/overrides.json
update the validation pattern for `SubscriptionName` property in `EventSubscription` schema to allow upper case characters.
```
Reproduced the current issue that upper case would fail SubscriptionName validation
1. modified overrides.json to add "/SubscriptionName": "redshift-event-subscription-contract-V2"
2. run contract test with cfn test -- -k contract_create_create
3. test failed
After updating SubscriptionName validation pattern
1. modified overrides.json to add "/SubscriptionName": "redshift-event-subscription-contract-V2"
2. run contract test with cfn test -- -k contract_create_create
3. test passed
```
> Update EventSubscription schema to allow upper case for SubscriptionName

- aws-redshift-scheduledaction/aws-redshift-scheduledaction.json
- aws-redshift-scheduledaction/docs/README.md
[Motivation]:
https://t.corp.amazon.com/P123773979/communication
[Description/Design]:
ScheduledAction pattern is different from service causing differences for customer between CLI and CFN. We are removing the pattern to keep it consistent with CLI
[Testing]:
1. local handler invocation with uppercase scheduled action name succeeds.
2. CTV2 works with lower case letters only. API converts name to lower case. CTV2 expects the input and output name to be same
3. Deployed stack using cloudformation deploy with uppercase scheduled action name and it deploys successfully.
> Fix for ScheduledActionName inconsistency in CFN with CLI

- aws-redshift-cluster/aws-redshift-cluster.json
- aws-redshift-clustersubnetgroup/aws-redshift-clustersubnetgroup.json
- aws-redshift-endpointaccess/aws-redshift-endpointaccess.json
- aws-redshift-endpointauthorization/aws-redshift-endpointauthorization.json
- aws-redshift-eventsubscription/aws-redshift-eventsubscription.json
- aws-redshift-scheduledaction/aws-redshift-scheduledaction.json
Uluru has launched a campaign to update relationship references for all cloudformation resources. This campaign would require all current CFN resources to add relationship references to its attributes/properties which can be referenced as a attribute of different CFN resource. This would help uluru to identify the dependency between CFN resources.
This change contains update to all relationship references of resources that are required to deploy Redshift CFN resources. This change is required as part of Uluru campaign
[Testing]:
1. Tested CTV2 for all resources in local account.
2. Verified that CTV2 passed for all resources in the account
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
> Updated Uluru Resource Relationship References for CFN Redshift Provisioned Resources

- aws-redshift-cluster/aws-redshift-cluster.json
- aws-redshift-cluster/docs/loggingproperties.md
- aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/ReadHandler.java
- aws-redshift-cluster/src/main/java/software/amazon/redshift/cluster/Translator.java
- aws-redshift-cluster/src/test/java/software/amazon/redshift/cluster/AbstractTestBase.java
- aws-redshift-cluster/src/test/java/software/amazon/redshift/cluster/CreateHandlerTest.java
- aws-redshift-cluster/src/test/java/software/amazon/redshift/cluster/UpdateHandlerTest.java
*Issue #, if available:* 
https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-redshift/issues/104
This change provides CFN support for enabling redshift audit logging with CloudWatch. We are adding 2 new parameters "LogDestinationType" and "LogExports" to the existing schema, which are used to setup CloudWatch logging for audit logging.
Manual testing and integration testing have been performed on cloudformation with all new changes.
> Support CloudWatch integration for AWS::Redshift::Cluster LoggingProperties

- aws-redshift-integration/pom.xml
- aws-redshift-integration/src/main/java/software/amazon/redshift/integration/BaseHandlerStd.java
- aws-redshift-integration/src/test/java/software/amazon/redshift/integration/BaseHandlerTest.java
The previous logic checks if the target cluster is stable by calling describe-clusters. In cross-account integration setup, the target might not have permission to call the API, in which case, we'll wait for 1 minute for the cluster to become available (usually takes a few seconds)
> Skip calling describe-clusters for cross-account integration

- aws-redshift-cluster/aws-redshift-cluster.json
Redshift now supports ra3.large nodeType.
https://aws.amazon.com/about-aws/whats-new/2024/10/amazon-redshift-ra3-large/
This CR contains change to include the ra3.large as list of allowed node types. This is blocking CDK to allow the node type on their end as they refer to the schema on CFN end.
> Added ra3.large to list of supported node types

- aws-redshift-clusterparametergroup/aws-redshift-clusterparametergroup.json
- aws-redshift-clusterparametergroup/resource-role.yaml
- aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/BaseHandlerStd.java
- aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/CreateHandler.java
- aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/DeleteHandler.java
- aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/ReadHandler.java
- aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/Translator.java
- aws-redshift-clusterparametergroup/src/main/java/software/amazon/redshift/clusterparametergroup/UpdateHandler.java
- aws-redshift-clusterparametergroup/src/test/java/software/amazon/redshift/clusterparametergroup/CreateHandlerTest.java
- aws-redshift-clusterparametergroup/src/test/java/software/amazon/redshift/clusterparametergroup/ReadHandlerTest.java
- aws-redshift-clusterparametergroup/template.yml
[Motivation]:
As part of the new initiative to support RBAC policies using Tags every resource on CFN need to support tags and should throw the appropriate errors in case of permission issues with creating/updating tags. This CR provides the integration for that change
[Testing]:
1. Verified that beta CT for tags are passing as suggested in the doc
2. Tested that local handlers are returning the response as expected
> Tags support added for cluster parameter group
